/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalistaRouteImport } from './routes/analista'
import { Route as FimRouteImport } from './routes/fim'
import { Route as AnalistaIndexRouteImport } from './routes/analista/index'
import { Route as AnalistaArquivosRouteImport } from './routes/analista/arquivos'
import { Route as AnalistaChecklistRouteImport } from './routes/analista/checklist'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalistaRoute = AnalistaRouteImport.update({
  id: '/analista',
  path: '/analista',
  getParentRoute: () => rootRouteImport,
} as any)
const FimRoute = FimRouteImport.update({
  id: '/fim',
  path: '/fim',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalistaIndexRoute = AnalistaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnalistaRoute,
} as any)
const AnalistaArquivosRoute = AnalistaArquivosRouteImport.update({
  id: '/arquivos',
  path: '/arquivos',
  getParentRoute: () => AnalistaRoute,
} as any)
const AnalistaChecklistRoute = AnalistaChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => AnalistaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analista': typeof AnalistaRouteWithChildren
  '/fim': typeof FimRoute
  '/analista/arquivos': typeof AnalistaArquivosRoute
  '/analista/checklist': typeof AnalistaChecklistRoute
  '/analista/': typeof AnalistaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fim': typeof FimRoute
  '/analista/arquivos': typeof AnalistaArquivosRoute
  '/analista/checklist': typeof AnalistaChecklistRoute
  '/analista': typeof AnalistaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analista': typeof AnalistaRouteWithChildren
  '/fim': typeof FimRoute
  '/analista/arquivos': typeof AnalistaArquivosRoute
  '/analista/checklist': typeof AnalistaChecklistRoute
  '/analista/': typeof AnalistaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analista'
    | '/fim'
    | '/analista/arquivos'
    | '/analista/checklist'
    | '/analista/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fim' | '/analista/arquivos' | '/analista/checklist' | '/analista'
  id:
    | '__root__'
    | '/'
    | '/analista'
    | '/fim'
    | '/analista/arquivos'
    | '/analista/checklist'
    | '/analista/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalistaRoute: typeof AnalistaRouteWithChildren
  FimRoute: typeof FimRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analista': {
      id: '/analista'
      path: '/analista'
      fullPath: '/analista'
      preLoaderRoute: typeof AnalistaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fim': {
      id: '/fim'
      path: '/fim'
      fullPath: '/fim'
      preLoaderRoute: typeof FimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analista/': {
      id: '/analista/'
      path: '/'
      fullPath: '/analista/'
      preLoaderRoute: typeof AnalistaIndexRouteImport
      parentRoute: typeof AnalistaRoute
    }
    '/analista/arquivos': {
      id: '/analista/arquivos'
      path: '/arquivos'
      fullPath: '/analista/arquivos'
      preLoaderRoute: typeof AnalistaArquivosRouteImport
      parentRoute: typeof AnalistaRoute
    }
    '/analista/checklist': {
      id: '/analista/checklist'
      path: '/checklist'
      fullPath: '/analista/checklist'
      preLoaderRoute: typeof AnalistaChecklistRouteImport
      parentRoute: typeof AnalistaRoute
    }
  }
}

interface AnalistaRouteChildren {
  AnalistaArquivosRoute: typeof AnalistaArquivosRoute
  AnalistaChecklistRoute: typeof AnalistaChecklistRoute
  AnalistaIndexRoute: typeof AnalistaIndexRoute
}

const AnalistaRouteChildren: AnalistaRouteChildren = {
  AnalistaArquivosRoute: AnalistaArquivosRoute,
  AnalistaChecklistRoute: AnalistaChecklistRoute,
  AnalistaIndexRoute: AnalistaIndexRoute,
}

const AnalistaRouteWithChildren = AnalistaRoute._addFileChildren(
  AnalistaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalistaRoute: AnalistaRouteWithChildren,
  FimRoute: FimRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
